// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: shipping.proto

package shipping

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_shipping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipping_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShipmentRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateShipmentRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	TrackingId    string                 `protobuf:"bytes,3,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentResponse) Reset() {
	*x = CreateShipmentResponse{}
	mi := &file_shipping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentResponse) ProtoMessage() {}

func (x *CreateShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentResponse.ProtoReflect.Descriptor instead.
func (*CreateShipmentResponse) Descriptor() ([]byte, []int) {
	return file_shipping_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShipmentResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateShipmentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateShipmentResponse) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

type GetShipmentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackingId    string                 `protobuf:"bytes,1,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentStatusRequest) Reset() {
	*x = GetShipmentStatusRequest{}
	mi := &file_shipping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentStatusRequest) ProtoMessage() {}

func (x *GetShipmentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentStatusRequest) Descriptor() ([]byte, []int) {
	return file_shipping_proto_rawDescGZIP(), []int{2}
}

func (x *GetShipmentStatusRequest) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

type GetShipmentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	StatusText    string                 `protobuf:"bytes,3,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentStatusResponse) Reset() {
	*x = GetShipmentStatusResponse{}
	mi := &file_shipping_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentStatusResponse) ProtoMessage() {}

func (x *GetShipmentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentStatusResponse) Descriptor() ([]byte, []int) {
	return file_shipping_proto_rawDescGZIP(), []int{3}
}

func (x *GetShipmentStatusResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetShipmentStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetShipmentStatusResponse) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

var File_shipping_proto protoreflect.FileDescriptor

const file_shipping_proto_rawDesc = "" +
	"\n" +
	"\x0eshipping.proto\x12\bshipping\"L\n" +
	"\x15CreateShipmentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"g\n" +
	"\x16CreateShipmentResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vtracking_id\x18\x03 \x01(\tR\n" +
	"trackingId\";\n" +
	"\x18GetShipmentStatusRequest\x12\x1f\n" +
	"\vtracking_id\x18\x01 \x01(\tR\n" +
	"trackingId\"j\n" +
	"\x19GetShipmentStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vstatus_text\x18\x03 \x01(\tR\n" +
	"statusText2\xc8\x01\n" +
	"\x0fShippingService\x12U\n" +
	"\x0eCreateShipment\x12\x1f.shipping.CreateShipmentRequest\x1a .shipping.CreateShipmentResponse\"\x00\x12^\n" +
	"\x11GetShipmentStatus\x12\".shipping.GetShipmentStatusRequest\x1a#.shipping.GetShipmentStatusResponse\"\x00B&Z$github.com/my-store/pkg/api/shippingb\x06proto3"

var (
	file_shipping_proto_rawDescOnce sync.Once
	file_shipping_proto_rawDescData []byte
)

func file_shipping_proto_rawDescGZIP() []byte {
	file_shipping_proto_rawDescOnce.Do(func() {
		file_shipping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipping_proto_rawDesc), len(file_shipping_proto_rawDesc)))
	})
	return file_shipping_proto_rawDescData
}

var file_shipping_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shipping_proto_goTypes = []any{
	(*CreateShipmentRequest)(nil),     // 0: shipping.CreateShipmentRequest
	(*CreateShipmentResponse)(nil),    // 1: shipping.CreateShipmentResponse
	(*GetShipmentStatusRequest)(nil),  // 2: shipping.GetShipmentStatusRequest
	(*GetShipmentStatusResponse)(nil), // 3: shipping.GetShipmentStatusResponse
}
var file_shipping_proto_depIdxs = []int32{
	0, // 0: shipping.ShippingService.CreateShipment:input_type -> shipping.CreateShipmentRequest
	2, // 1: shipping.ShippingService.GetShipmentStatus:input_type -> shipping.GetShipmentStatusRequest
	1, // 2: shipping.ShippingService.CreateShipment:output_type -> shipping.CreateShipmentResponse
	3, // 3: shipping.ShippingService.GetShipmentStatus:output_type -> shipping.GetShipmentStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shipping_proto_init() }
func file_shipping_proto_init() {
	if File_shipping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipping_proto_rawDesc), len(file_shipping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipping_proto_goTypes,
		DependencyIndexes: file_shipping_proto_depIdxs,
		MessageInfos:      file_shipping_proto_msgTypes,
	}.Build()
	File_shipping_proto = out.File
	file_shipping_proto_goTypes = nil
	file_shipping_proto_depIdxs = nil
}
